import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`wrap-landing`}>

        <div className={`gradient`}>
        </div>

        <div className={`landing-container`}>
          <div className={`hero-container`} data-aos="fade-left">
            <h1>i am a frontend web dev</h1>
            <p>and this is my profile</p>

            <div className="cta">
              <Link href="/about_me" >
                <span>about me</span>
                <svg width="13px" height="10px" viewBox="0 0 13 10">
                  <path d="M1,5 L11,5"></path>
                  <polyline points="8 1 12 5 8 9"></polyline>
                </svg>
              </Link>
            </div>
          </div>
        </div>

      </main>
    </>
  )
}
