import Head from 'next/head';
import Image from 'next/image';
import { PersonalCard } from '@/components/CardTemplate_1';


export default function Portfolio() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`wrap-portfolio`}>
        <div className={`portfolio-header`}>
          <h1>Showcase of My Projects</h1>
          <p>This is a showcase of projects I had previously involved in</p>
        </div>
        <div className={`portfolio-container-1`}>
          <PersonalCard 
            background_image={`/assets/images/bgimage-03.png`}

            main_title={`Current Personal Web`}
            // main_title_desc={`This is my portfolio made with NextJS`}

            text_title={`Tools and Languages:`}
          />
        </div>
      </main>
    </>
  )
}
