import Head from 'next/head';
import Image from 'next/image';
// import { PersonalCard } from '@/components/CardTemplate_1';
import { Card, Col, Row, Grid, Text, Popover, Button } from "@nextui-org/react";
// import { Projects1 } from '@/components/Portfolio_Card1';
import { ProjectsTemplate2 } from '@/components/Portfolio_Card2';
import { AiFillFire } from "react-icons/ai";
import { ProjectsTemplate3 } from '@/components/Portfolio_Card3';


export default function Portfolio() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`wrap-portfolio`}>
        {/* <div className={`portfolio-header`}>
          <h1>Showcase of My Projects</h1>
          <p>This is a showcase of projects I was previously involved in</p>
        </div> */}
        <div className="portfolio-header" >
          <h1 data-aos="fade-down">Showcase of My Projects</h1>
          <p data-aos="fade-down">This is a showcase of projects I was previously involved in.</p>
        </div>

        {/* <div className={`portfolio-container-1`}>
          <PersonalCard 
            background_image={`/assets/images/bgimage-03.png`}

            main_title={`Current Personal Web`}
            main_title_desc={`This is my portfolio made with NextJS`}

            text_title={`Tools and Languages:`}
          />
        </div> */}

        <div className={`portfolio-container-1`}>
          <div className={`port-card-1`}>
            <h3>current personal web </h3>
            <div className={`port-card-1-item`}>
              <span className="port-card-1-item-title">Tools and Languages</span>

              <div className="port-card-1-item-content">
                <Popover placement={"top-left"} className={``}>
                  <Popover.Trigger>
                    <Card.Image src="/assets/images/tools-icons/nextjs.png" className={`card-icon-type1`}
                      css={{ bg: "black", br: "10px" }} height={40} width={40} alt="Personal Web Icon"
                    />
                  </Popover.Trigger>
                  <Popover.Content isBlurred css={{ bgBlur: "#0f1114b5", br: "10px" }} >
                    <Text css={{ p: "10px" }} color="#fff" size={12}>Next.js by Vercel - The React Framework</Text>
                  </Popover.Content>
                </Popover>

                <Popover placement={"top-left"} className={``}>
                  <Popover.Trigger>
                    <Card.Image src="/assets/images/tools-icons/nextui.png" className={`card-icon-type1`}
                      css={{ bg: "black", br: "10px" }} height={40} width={40} alt="Personal Web Icon"
                    />
                  </Popover.Trigger>
                  <Popover.Content isBlurred css={{ bgBlur: "#0f1114b5", br: "10px" }} >
                    <Text css={{ p: "10px" }} color="#fff" size={12}>NextUI - Beautiful, fast and modern React UI Library</Text>
                  </Popover.Content>
                </Popover>

                <Popover placement={"top-left"} className={``} variant="bordered">
                  <Popover.Trigger>
                    <Card.Image src="/assets/images/tools-icons/sass_01.png" className={`card-icon-type1`}
                      css={{ bg: "black", br: "10px" }} height={40} width={40} alt="Personal Web Icon"
                    />
                  </Popover.Trigger>
                  <Popover.Content isBlurred css={{ bgBlur: "#0f1114b5", br: "10px" }} >
                    <Text css={{ p: "10px" }} color="#fff" size={12}>Sass: Syntactically Awesome Style Sheets</Text>
                  </Popover.Content>
                </Popover>
              </div>
            </div>
          </div>
          
          {/* <div className="port-card-2" data-aos="fade-left">
            <h4 >Spice Level (difficulty)</h4>

            <div className="port-card-2-item">
              <div className="port-card-2-item-1" >
                <AiFillFire className="port-card-2-item-icon1" />
                Low
              </div>
              <div className="port-card-2-item-2" >
                <AiFillFire className="port-card-2-item-icon1" />
                Medium
              </div>
              <div className="port-card-2-item-3" >
                <AiFillFire className="port-card-2-item-icon1" />
                Hot
              </div>
              <div className="port-card-2-item-4" >
                <AiFillFire className="port-card-2-item-icon1" />
                Extra Hot
              </div>
            </div>
          </div> */}
        </div>

        <section className={`portfolio-content-1`}>
          {/* <h2>Past Projects</h2> */}
          {/* <div className={`portfolio-content-1-container-1`} >
            <Projects1 />
          </div> */}

          {/* <ProjectsTemplate2 /> */}

          <ProjectsTemplate3 />
        </section>

        <section className={`portfolio-content-2`}>
          <h2 data-aos="fade-up">My Skills</h2>
          <p data-aos="fade-up">This section is about the tools I used and why I use them</p>

          <h3 data-aos="fade-up">Frameworks and Styling</h3>
          <div className="port-skl-1">
            <div className="port-skl-item-1 nextjs" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/nextjs.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>NextJS</h3>
                  <p>- To build landing / ecommerce / crm frontend projects</p>
                </div>
              </div>
            </div>

            <div className="port-skl-item-1 reactjs" data-aos="fade-up"> 
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/reactjs.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>ReactJS</h3>
                  <p>- To build landing / ecommerce frontend projects</p>
                </div>
              </div>
            </div>

            <div className="port-skl-item-1 sass" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/sass_01.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>SASS/SCSS</h3>
                  <p>- To style frontend for more flexibility with some animations</p>
                </div>
              </div>
            </div>

            <div className="port-skl-item-1 tailwind" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/tailwindcss.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>TailwindCSS</h3>
                  <p>- To style frontend inside classes</p>
                  <p>PS: I dont really like to use tailwind, felt messy</p>
                </div>
              </div>
            </div>
          </div>

          <div className="port-skl-2">
            <div className="port-skl-2-1">
              <h3 data-aos="fade-up">Content Management System</h3>
              <div>
                <div className="port-skl-item-1 wordpress" data-aos="fade-up">
                  <div className="port-skl-item-1-img">
                    <Image src={`/assets/images/tools-icons/wordpress.png`} alt="portfolio" 
                      width={100} height={100}
                    /> 
                  </div>
                  <div className="port-skl-item-1-info">
                    <div>
                      <h3>Wordpress</h3>
                      <p>- Landing/E-commerce</p>
                      <p>- Manage & optimize SEO</p>
                    </div>
                  </div>
                </div>
                <div className="port-skl-item-1 divi" data-aos="fade-up">
                  <div className="port-skl-item-1-img">
                    <Image src={`/assets/images/tools-icons/divi.png`} alt="portfolio" 
                      width={100} height={100}
                    /> 
                  </div>
                  <div className="port-skl-item-1-info">
                    <div>
                      <h3>Divi by ElegantThemes</h3>
                      <p>- A Themebuilder with wide range of drag and drop components</p>
                      <p>- Easy to use</p>
                    </div>
                  </div>
                </div>
                <div className="port-skl-item-1 smartslider" data-aos="fade-up">
                  <div className="port-skl-item-1-img">
                    <Image src={`/assets/images/tools-icons/smartslider.png`} alt="portfolio" 
                      width={100} height={100}
                    /> 
                  </div>
                  <div className="port-skl-item-1-info">
                    <div>
                      <h3>SmartSlider3</h3>
                      <p>- WordPress slider plugin</p>
                      <p>- To create slider, carousel and block in Wordpress</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="port-skl-2-1">
              <h3 data-aos="fade-up">CSS Frameworks</h3>
              <div>
                <div className="port-skl-item-1 reactjs" data-aos="fade-up">
                  <div className="port-skl-item-1-img">
                    <Image src={`/assets/images/tools-icons/reactbootstrap.png`} alt="portfolio" 
                      width={100} height={100}
                    /> 
                  </div>
                  <div className="port-skl-item-1-info">
                    <div>
                      <h3>React Bootstrap</h3>
                      <p>- To build modals / carousels / accordions quicker</p>
                    </div>
                  </div>
                </div>
                <div className="port-skl-item-1 antdesign" data-aos="fade-up">
                  <div className="port-skl-item-1-img">
                    <Image src={`/assets/images/tools-icons/antdesign.png`} alt="portfolio" 
                      width={100} height={100}
                    /> 
                  </div>
                  <div className="port-skl-item-1-info">
                    <div>
                      <h3>Ant Design</h3>
                      <p>- To build modals / carousels / accordions / notifications / image-preview quicker</p>
                    </div>
                  </div>
                </div>
                <div className="port-skl-item-1 evergreen" data-aos="fade-up">
                  <div className="port-skl-item-1-img">
                    <Image src={`/assets/images/tools-icons/evergreen.png`} alt="portfolio" 
                      width={100} height={100}
                    /> 
                  </div>
                  <div className="port-skl-item-1-info">
                    <div>
                      <h3>Evergreen</h3>
                      <p>- To build modals / carousels / accordions / notifications / image-preview quicker</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <h3 data-aos="fade-up">SEO</h3>
          <div className="port-skl-1">
            <div className="port-skl-item-1 google" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/google-tagmanager.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Google Tag Manager</h3>
                  <p>- Setup Google SEO tools</p>
                  <p>PS: I need more experience</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 google" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/google-analytics.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Google Analytics</h3>
                  <p>- Monitor websites traffics and analytics</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 google" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/google-searchconsole.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Google Search Console</h3>
                  <p>- Manage websites indexing status, search queries, crawling errors and optimize visibility</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 semrush" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/semrush.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>SEMRush</h3>
                  <p>- Monitor websites traffics, SEO suggestions</p>
                </div>
              </div>
            </div>
          </div>

          <h3 data-aos="fade-up">Others</h3>
          <div className="port-skl-1">
            <div className="port-skl-item-1 tawkto" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/tawkto.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Tawk.to</h3>
                  <p>- LiveChat with clients/users based on ticketing system</p>
                  <p>- Wrote knowledge base articles for events</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 canva" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/canva.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Canva</h3>
                  <p>- Edit logos, png and any other images that does not fit the projects</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 krita" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/krita.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Krita</h3>
                  <p>- Krita is a professional FREE and open source painting program</p>
                  <p>- Edit logos or images that Canva cannot provide</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 figma" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/figma.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Figma</h3>
                  <p>- Build UI/UX for mobile app and websites</p>
                  <p>PS: I need more experience</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 zeplin" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/zeplin.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Zeplin</h3>
                  <p>- To refer UI for building websites</p>
                  <p>- Join existing projects for UI/UX</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 emailjs" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/emailjs.png`} alt="portfolio" 
                  width={80} height={80}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>EmailJS</h3>
                  <p>- Used for contact forms</p>
                  <p>- To send enquiries from contact forms as email to client</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 emailjs" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/metabusiness.png`} alt="portfolio" 
                  width={80} height={80}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Meta Business Suite</h3>
                  <p>- Setup Messenger widget</p>
                  <p>- Learnt about ads, analytics and live streams</p>
                </div>
              </div>
            </div>
          </div>

          <h3 data-aos="fade-up">Non Work Stuffs</h3>
          <div className="port-skl-1">
            <div className="port-skl-item-1 twitch" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/twitch.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Twitch</h3>
                  <p>- Setup environment for live streams and moderations</p>
                  <p>- Moderations for a few streamers and create chat guidelines to obey by viewers</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 streamlabs" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/streamlabs.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>Streamlabs</h3>
                  <p>- Setup gaming live streams to be broadcasted on Twitch, YouTube or Facebook</p>
                  <p>- Designed themes for stream (Eg. Amount of followers / subscribers, Camera, Stream Notifications)</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 streamelements" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/streamelements.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>StreamElements</h3>
                  <p>- Setup dashboard for stream&apos;s revenue, merch and stream analytics</p>
                  <p>- Create stream notifications (Eg. New followers / subscribers)</p>
                </div>
              </div>
            </div>
            <div className="port-skl-item-1 vsdc" data-aos="fade-up">
              <div className="port-skl-item-1-img">
                <Image src={`/assets/images/tools-icons/vsdc.png`} alt="portfolio" 
                  width={100} height={100}
                /> 
              </div>
              <div className="port-skl-item-1-info">
                <div>
                  <h3>VSDC Video Editor</h3>
                  <p>- Video editing software</p>
                  <p>- Edited gaming videos to be published on YouTube</p>
                  <p>PS: Still trying to learn more about video editing</p>
                </div>
              </div>
            </div>
          </div>

        </section>
      </main>
    </>
  )
}
