import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { useRouter } from "next/router";
import dynamic from 'next/dynamic';
const AnimatedCursor = dynamic(() => import('react-animated-cursor'), {
  ssr: false
});

export default function Navbar() {
  const router = useRouter();

  return (
    <>
      {/* <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

        
      <AnimatedCursor
        innerSize={8}
        outerSize={35}
        innerScale={1}
        outerScale={2}
        outerAlpha={0}
        hasBlendMode={true}
        outerStyle={{
          border: '3px solid var(--cursor-color)'
        }}
        innerStyle={{
          backgroundColor: 'var(--cursor-color)'
        }}
      />

      <nav className={`wrap-navbar `}>

        <div className="navbar-container">
          <div className="logo-container">
            <Link href='/' className="navbar-logo" target='_parent'>
              <Image
                src="/assets/images/cqihan-03.png"
                alt="Vercel Logo"
                width={150}
                height={70}
                priority
              />
            </Link>
          </div>

          <ul className='nav-menu'>
            <li className='nav-item'>
              <Link href='/' className={`${router.pathname == "/" ? "active" : ""} nav-links`} target='_top'>
                  home
              </Link>
            </li>

            <li className='nav-item'>
              <Link href='/about_me' className={`${router.pathname == "/about_me" ? "active" : ""} nav-links`} target='_top'>
                  about me
              </Link>
            </li>

            <li className='nav-item'>
              <Link href='/portfolio' className={`${router.pathname == "/portfolio" ? "active" : ""} nav-links`} target='_top'>
                  portfolio
              </Link>
            </li>
          </ul>
        </div>
      </nav>

      {/* <nav className={`wrap-navbar-mobile `}>

        <div className="navbar-container">
          <div className="logo-container">
            <Link href='/' className="navbar-logo" target='_parent'>
              <Image
                src="/assets/images/cqihan-03.png"
                alt="Vercel Logo"
                width={150}
                height={70}
                priority
              />
            </Link>
          </div>

          <ul className='nav-menu'>
            <li className='nav-item'>
              <Link href='/' className={`${router.pathname == "/" ? "active" : ""} nav-links`} target='_top'>
                  home
              </Link>
            </li>

            <li className='nav-item'>
              <Link href='/about_me' className={`${router.pathname == "/about_me" ? "active" : ""} nav-links`} target='_top'>
                  about me
              </Link>
            </li>

            <li className='nav-item'>
              <Link href='/portfolio' className={`${router.pathname == "/portfolio" ? "active" : ""} nav-links`} target='_top'>
                  portfolio
              </Link>
            </li>
          </ul>
        </div>
      </nav> */}
    </>
  )
}
